[mgr]
# to override a default keymap use prepend
prepend_keymap = [
	{ on = ["f"], run = "plugin zoxide", desc = "Run zoxide" },
	{ on = ["H"], run = "plugin duckdb -1", desc = "Scroll one column to the left" },
	{ on = ["L"], run = "plugin duckdb +1", desc = "Scroll one column to the right" },
	{ on = ["g", "o"], run = "plugin duckdb -open", desc = "Open with duckdb" },
	{ on = ["g", "u"], run = "plugin duckdb -ui", desc = "Open with duckdb UI" },
]

[input]
prepend_keymap = [
	{ on = [ "<C-j>" ], run = "close --submit", desc = "Submit the input" },
]
