# Seek
h seek -1 exact
l seek 1 exact
H seek -5 exact
L seek 5 exact
^ seek 0 absolute
$ seek 100 absolute-percent

# Speed
+ add speed 0.1
- add speed -0.1
= set speed 1.0

# Chapters
[ add chapter -1
] add chapter 1

w screenshot
