# examples
# [mgr]
# prepend_keymap = [
# 	{ on = "<C-a>", run = "my-cmd1", desc = "Single command with `Ctrl + a`" },
# ]
# append_keymap = [
# 	{ on = [ "g", "b" ], run = "my-cmd2",          desc = "Single command with `g => b`" },
# 	{ on = "c",          run = [ "cmd1", "cmd2" ], desc = "Multiple commands with `c`" }
# ]
